# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bootcamp}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremy Woertink"]
  s.date = %q{2011-06-15}
  s.default_executable = %q{bootcamp}
  s.description = %q{Check out the README file for more info}
  s.email = %q{jeremywoertink@gmail.com}
  s.executables = ["bootcamp"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "LICENSE.txt",
    "NOTES",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/bootcamp",
    "bootcamp.gemspec",
    "lib/bootcamp.rb",
    "lib/bootcamp/armory.rb",
    "lib/bootcamp/depot.rb",
    "lib/bootcamp/drill_instructor.rb",
    "lib/bootcamp/manifest/bootstrap.rb",
    "lib/bootcamp/manifest/core.rb",
    "lib/bootcamp/manifest/dojo.rb",
    "lib/bootcamp/manifest/html.rb",
    "lib/bootcamp/manifest/jquery.rb",
    "lib/bootcamp/manifest/midori.rb",
    "lib/bootcamp/manifest/mootools.rb",
    "lib/bootcamp/manifest/prototype.rb",
    "lib/bootcamp/recruit.rb",
    "spec/bootcamp_spec.rb",
    "spec/spec_helper.rb",
    "vendor/core.js",
    "vendor/dojo.js",
    "vendor/jquery.js",
    "vendor/midori.js",
    "vendor/mootools.js",
    "vendor/prototype.js",
    "vendor/test_suites/jasmine/SpecRunner.html",
    "vendor/test_suites/jasmine/lib/jasmine-1.0.2/MIT.LICENSE",
    "vendor/test_suites/jasmine/lib/jasmine-1.0.2/jasmine-html.js",
    "vendor/test_suites/jasmine/lib/jasmine-1.0.2/jasmine.css",
    "vendor/test_suites/jasmine/lib/jasmine-1.0.2/jasmine.js",
    "vendor/test_suites/jasmine/spec/PlayerSpec.js",
    "vendor/test_suites/jasmine/spec/SpecHelper.js",
    "vendor/test_suites/jasmine/src/Player.js",
    "vendor/test_suites/jasmine/src/Song.js",
    "vendor/test_suites/jspec/History.md",
    "vendor/test_suites/jspec/Manifest",
    "vendor/test_suites/jspec/README.md",
    "vendor/test_suites/jspec/Rakefile",
    "vendor/test_suites/jspec/bin/jspec",
    "vendor/test_suites/jspec/jspec.gemspec",
    "vendor/test_suites/jspec/lib/images/bg.png",
    "vendor/test_suites/jspec/lib/images/hr.png",
    "vendor/test_suites/jspec/lib/images/loading.gif",
    "vendor/test_suites/jspec/lib/images/sprites.bg.png",
    "vendor/test_suites/jspec/lib/images/sprites.png",
    "vendor/test_suites/jspec/lib/images/vr.png",
    "vendor/test_suites/jspec/lib/jspec.css",
    "vendor/test_suites/jspec/lib/jspec.growl.js",
    "vendor/test_suites/jspec/lib/jspec.jquery.js",
    "vendor/test_suites/jspec/lib/jspec.js",
    "vendor/test_suites/jspec/lib/jspec.shell.js",
    "vendor/test_suites/jspec/lib/jspec.timers.js",
    "vendor/test_suites/jspec/lib/jspec.xhr.js",
    "vendor/test_suites/jspec/spec/commands/example_command.rb",
    "vendor/test_suites/jspec/spec/dom.html",
    "vendor/test_suites/jspec/spec/fixtures/test.html",
    "vendor/test_suites/jspec/spec/fixtures/test.json",
    "vendor/test_suites/jspec/spec/fixtures/test.xml",
    "vendor/test_suites/jspec/spec/node.js",
    "vendor/test_suites/jspec/spec/rhino.js",
    "vendor/test_suites/jspec/spec/ruby/bin/init_spec.rb",
    "vendor/test_suites/jspec/spec/ruby/bin/install_spec.rb",
    "vendor/test_suites/jspec/spec/ruby/bin/run_spec.rb",
    "vendor/test_suites/jspec/spec/ruby/bin/shell_spec.rb",
    "vendor/test_suites/jspec/spec/ruby/bin/spec_helper.rb",
    "vendor/test_suites/jspec/spec/ruby/bin/update_spec.rb",
    "vendor/test_suites/jspec/spec/server.html",
    "vendor/test_suites/jspec/spec/server.rb",
    "vendor/test_suites/jspec/spec/support/env.js",
    "vendor/test_suites/jspec/spec/support/jquery.js",
    "vendor/test_suites/jspec/spec/unit/helpers.js",
    "vendor/test_suites/jspec/spec/unit/spec.fixtures.js",
    "vendor/test_suites/jspec/spec/unit/spec.grammar-less.js",
    "vendor/test_suites/jspec/spec/unit/spec.grammar.js",
    "vendor/test_suites/jspec/spec/unit/spec.jquery.js",
    "vendor/test_suites/jspec/spec/unit/spec.jquery.xhr.js",
    "vendor/test_suites/jspec/spec/unit/spec.js",
    "vendor/test_suites/jspec/spec/unit/spec.matchers.js",
    "vendor/test_suites/jspec/spec/unit/spec.modules.js",
    "vendor/test_suites/jspec/spec/unit/spec.shared-behaviors.js",
    "vendor/test_suites/jspec/spec/unit/spec.utils.js",
    "vendor/test_suites/jspec/spec/unit/spec.xhr.js",
    "vendor/test_suites/jspec/src/browsers.rb",
    "vendor/test_suites/jspec/src/helpers.rb",
    "vendor/test_suites/jspec/src/installables.rb",
    "vendor/test_suites/jspec/src/project.rb",
    "vendor/test_suites/jspec/src/routes.rb",
    "vendor/test_suites/jspec/src/server.rb",
    "vendor/test_suites/jspec/support/js.jar",
    "vendor/test_suites/jspec/templates/default/History.md",
    "vendor/test_suites/jspec/templates/default/Readme.md",
    "vendor/test_suites/jspec/templates/default/lib/yourlib.js",
    "vendor/test_suites/jspec/templates/default/spec/commands/example_command.rb",
    "vendor/test_suites/jspec/templates/default/spec/dom.html",
    "vendor/test_suites/jspec/templates/default/spec/node.js",
    "vendor/test_suites/jspec/templates/default/spec/rhino.js",
    "vendor/test_suites/jspec/templates/default/spec/server.html",
    "vendor/test_suites/jspec/templates/default/spec/server.rb",
    "vendor/test_suites/jspec/templates/default/spec/unit/spec.helper.js",
    "vendor/test_suites/jspec/templates/default/spec/unit/spec.js",
    "vendor/test_suites/jspec/templates/node/History.md",
    "vendor/test_suites/jspec/templates/node/Readme.md",
    "vendor/test_suites/jspec/templates/node/lib/yourlib.js",
    "vendor/test_suites/jspec/templates/node/spec/node.js",
    "vendor/test_suites/jspec/templates/node/spec/unit/spec.helper.js",
    "vendor/test_suites/jspec/templates/node/spec/unit/spec.js",
    "vendor/test_suites/jspec/templates/rails/commands/example_commands.rb",
    "vendor/test_suites/jspec/templates/rails/dom.html",
    "vendor/test_suites/jspec/templates/rails/rhino.js",
    "vendor/test_suites/jspec/templates/rails/server.html",
    "vendor/test_suites/jspec/templates/rails/server.rb",
    "vendor/test_suites/jspec/templates/rails/unit/spec.helper.js",
    "vendor/test_suites/jspec/templates/rails/unit/spec.js",
    "vendor/test_suites/qunit/README.md",
    "vendor/test_suites/qunit/package.json",
    "vendor/test_suites/qunit/qunit/qunit.css",
    "vendor/test_suites/qunit/qunit/qunit.js",
    "vendor/test_suites/qunit/test/headless.html",
    "vendor/test_suites/qunit/test/index.html",
    "vendor/test_suites/qunit/test/logs.html",
    "vendor/test_suites/qunit/test/logs.js",
    "vendor/test_suites/qunit/test/same.js",
    "vendor/test_suites/qunit/test/test.js"
  ]
  s.homepage = %q{http://github.com/jwoertink/bootcamp}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{A gem to manage JavaScript Plugins}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<git>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<highline>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<git>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<highline>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<git>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<highline>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
  end
end

